name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install and Build
      env: |
        BASEPATH: '/${{ github.event.repository.name }}/'
      run: |
        npm ci
        npm run build
        touch dist/.nojekyll
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages
        folder: dist
